
version: '3.8'

services:
  demorestaurant:
    image: postgres:latest
    restart: "no"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: name_usuario
      POSTGRES_USER: pass_usuario
      POSTGRES_DB: name_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
   